Make the current Python version a hard dependency

diff --git a/package/PKGBUILD b/package/PKGBUILD
--- a/package/PKGBUILD
+++ b/package/PKGBUILD
@@ -17,6 +17,43 @@ source=("git+${url}.git")
 sha1sums=("SKIP")
 
 
+SoftwareVersion () {
+	cd "${srcdir}/optimus-manager"
+	local Commits; Commits="$(git rev-list --count HEAD)"
+
+	if [[ -n "${Commits}" ]]; then
+		if [[ "${Commits}" -le 1 ]]; then
+			echo 0
+		else
+			echo "${Commits}"
+		fi
+	fi
+}
+
+
+PythonVersion="$(
+	pacman --sync --print-format "%v" python |
+	cut --delimiter='-' --fields=1
+)"
+
+
+pkgver () {
+	local SoftwareVersion; SoftwareVersion="$(SoftwareVersion)"
+
+	if [[ -z "${SoftwareVersion}" ]]; then
+		echo "Failed to retrieve: SoftwareVersion" >&2
+		false
+	elif [[ -z "${PythonVersion}" ]]; then
+		echo "Failed to retrieve: PythonVersion" >&2
+		false
+	else
+		printf "%s.python%s" \
+			"${SoftwareVersion}" \
+			"${PythonVersion}"
+	fi
+}
+
+
 conflicts=(
 	"bumblebee"
 	"envycontrol"
@@ -29,7 +66,7 @@ conflicts=(
 
 
 provides=(
-	"optimus-manager=${pkgver}"
+	"optimus-manager=${epoch}:${pkgver}"
 )
 
 
@@ -46,7 +83,7 @@ depends=(
 	"dbus-python"
 	"glxinfo"
 	"NVIDIA-MODULE"
-	"python"
+	"python=${PythonVersion}"
 	"xorg-xrandr"
 )
 
@@ -72,44 +109,6 @@ backup=(
 	'etc/optimus-manager/xsetup-hybrid.sh'
 	'var/lib/optimus-manager/persistent/startup_mode'
 )
-
-
-SoftwareVersion () {
-	cd "${srcdir}/optimus-manager"
-	local Commits; Commits="$(git rev-list --count HEAD)"
-
-	if [[ -n "${Commits}" ]]; then
-		if [[ "${Commits}" -le 1 ]]; then
-			echo 0
-		else
-			echo "${Commits}"
-		fi
-	fi
-}
-
-
-PythonVersion () {
-	pacman --sync --print-format "%v" python |
-	cut --delimiter='.' --fields=1,2
-}
-
-
-pkgver () {
-	local SoftwareVersion; SoftwareVersion="$(SoftwareVersion)"
-	local PythonVersion; PythonVersion="$(PythonVersion)"
-
-	if [[ -z "${SoftwareVersion}" ]]; then
-		echo "Failed to retrieve: SoftwareVersion" >&2
-		false
-	elif [[ -z "${PythonVersion}" ]]; then
-		echo "Failed to retrieve: PythonVersion" >&2
-		false
-	else
-		printf "%s.python%s" \
-			"${SoftwareVersion}" \
-			"${PythonVersion}"
-	fi
-}
 
 
 prepare () {
